### PR TITLE
update eciYali based on 4.1.1

### PR DESCRIPTION
**Pull request by automator-metatlas**
MATLAB is selecting SOFTWARE OPENGL rendering.

                                                                              < M A T L A B (R) >
                                                                    Copyright 1984-2020 The MathWorks, Inc.
                                                                R2020b Update 3 (9.9.0.1538559) 64-bit (glnxa64)
                                                                               November 23, 2020

 
To get started, type doc.
For product information, visit www.mathworks.com.
 

***************************************************************
   GECKO: Adding enzyme constraints to a genome-scale model
***************************************************************

Getting genome-scale model ready... Done!

==================
Generating ecModel:
==================
Retrieving EC numbers....................... Done!
Matching kcats....................... Done!
Adding enzymes to reactions................................ Done!
Improving model with curated data............................................ Done!

==============================================================
Generating ecModel with shared pool assumption (ecModel_batch):
==============================================================
prot_abundance file is empty or not available. A default value of f=0.5 is set instead
Matching data to enzymes in model... Done!
Total protein amount measured = 0 g/gDW
Total enzymes measured = 0 enzymes
Enzymes in model with 0 g/gDW = 0 enzymes
Total protein amount not measured = 0.5493 g/gDW
Total enzymes not measured = 647 enzymes
Total protein in model = 0.5493 g/gDW

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

The ECmodel is not overconstrained.
***************************************************************
Fitting sigma factor...
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

.
--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

. Done!
[Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information, click <a href="matlab:opengl('problems')">here</a>.] 

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

--------------------------------------------
Warning: your license will expire in 7 days
--------------------------------------------

Saving simulation results files...
File successfully saved.
Sigma factor (fitted for growth on glucose): 0.49

=============
Saving models:
=============
Saving eciYali4.1.1:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.
Saving eciYali_batch4.1.1:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
I'm not sure which license this is, but I'll deal with it @IVANDOMENZAIN

**Comment by IVANDOMENZAIN** [comment]
> I'm not sure which license this is, but I'll deal with it @IVANDOMENZAIN

In this part of the pipeline GECKO is solving a lot of LP problems, so to me it looks like all the calls to the RAVEN `solveLP` function (which relies on GUROBI).

**Comment by mihai-sysbio** [comment]
I guess we'll see in the next run if it was Gurobi or not.

**Comment by IVANDOMENZAIN** [comment]
> I guess we'll see in the next run if it was Gurobi or not.

Yes, so far the same happened in this newly created [PR for eciML1515](https://github.com/SysBioChalmers/ecModels/pull/39), really think that it is about the solver, which is also good because then we have a very sound indicator of when the update is needed for such license.

**Pull request closed without merging**
