### PR TITLE
chore: update eciSM966 based on v1.0.0

### PR DESCRIPTION
**Pull request by IVANDOMENZAIN**
@mihai-sysbio As you can see, a branch was created, returning the expected outputs, however the corresponding PR was not opened by the automator, same as with [ecYeastGEM](https://github.com/SysBioChalmers/ecModels/pull/40). 

This PR has been created manually.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Alright, this was in the logs when creating a PR:

> Error creating pull request: Unprocessable Entity (HTTP 422)
body is too long (maximum is 65536 characters)

The log was full of license expiry warnings, so I'm going to double-check the licenses and mark this as a non-issue.

**Comment by mihai-sysbio** [comment]
@IVANDOMENZAIN I had closed the branch, only later to remember that you wanted to keep them open to look at the models that were obtained. I'll leave the closing/branch deletion up to you.

**Comment by IVANDOMENZAIN** [comment]
> Alright, this was in the logs when creating a PR:
> 
> > Error creating pull request: Unprocessable Entity (HTTP 422)
> > body is too long (maximum is 65536 characters)
> 
> The log was full of license expiry warnings, so I'm going to double-check the licenses and mark this as a non-issue.

Good to know this!

**Comment by IVANDOMENZAIN** [comment]
> @IVANDOMENZAIN I had closed the branch, only later to remember that you wanted to keep them open to look at the models that were obtained. I'll leave the closing/branch deletion up to you.

Thank you!

**Pull request closed without merging**
