### PR TITLE
update ecYeastGEM based on v8.4.2

### PR DESCRIPTION
**Pull request by automator-metatlas**
MATLAB is selecting SOFTWARE OPENGL rendering.

                                                                              < M A T L A B (R) >
                                                                    Copyright 1984-2020 The MathWorks, Inc.
                                                                R2020b Update 3 (9.9.0.1538559) 64-bit (glnxa64)
                                                                               November 23, 2020

 
To get started, type doc.
For product information, visit www.mathworks.com.
 

      _____   _____   _____   _____     _____     |
     /  ___| /  _  \ |  _  \ |  _  \   / ___ \    |   COnstraint-Based Reconstruction and Analysis
     | |     | | | | | |_| | | |_| |  | |___| |   |   The COBRA Toolbox - 2021
     | |     | | | | |  _  { |  _  /  |  ___  |   |
     | |___  | |_| | | |_| | | | \ \  | |   | |   |   Documentation:
     \_____| \_____/ |_____/ |_|  \_\ |_|   |_|   |   http://opencobra.github.io/cobratoolbox
                                                  | 

 > Checking if git is installed ...  Done (version: 2.25.1).
 > Checking if the repository is tracked using git ...  Done.
 > Checking if curl is installed ...  Done.
 > Checking if remote can be reached ...  Done.
 > Initializing and updating submodules (this may take a while)... Done.
 > Adding all the files of The COBRA Toolbox ...  Done.
 > Define CB map output... set to svg.
 > TranslateSBML is installed and working properly.
 > Configuring solver environment variables ...
   - [----] ILOG_CPLEX_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] GUROBI_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] TOMLAB_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] MOSEK_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   Done.
 > Checking available solvers and solver interfaces ... Done.
 > Setting default solvers ... Done.
 > Saving the MATLAB path ... Done.
   - The MATLAB path was saved as ~/pathdef.m.

 > Summary of available solvers and solver interfaces

			Support 	   LP 	 MILP 	   QP 	 MIQP 	  NLP
	----------------------------------------------------------------------
	gurobi       	active        	    1 	    1 	    1 	    1 	    -
	ibm_cplex    	active        	    0 	    0 	    0 	    0 	    -
	tomlab_cplex 	active        	    0 	    0 	    0 	    0 	    -
	glpk         	active        	    1 	    1 	    - 	    - 	    -
	mosek        	active        	    0 	    - 	    0 	    - 	    -
	matlab       	active        	    0 	    - 	    - 	    - 	    0
	pdco         	active        	    1 	    - 	    1 	    - 	    -
	quadMinos    	active        	    0 	    - 	    - 	    - 	    -
	dqqMinos     	active        	    0 	    - 	    0 	    - 	    -
	cplex_direct 	active        	    0 	    0 	    0 	    - 	    -
	cplexlp      	active        	    0 	    - 	    - 	    - 	    -
	qpng         	passive       	    - 	    - 	    1 	    - 	    -
	tomlab_snopt 	passive       	    - 	    - 	    - 	    - 	    0
	lp_solve     	legacy        	    1 	    - 	    - 	    - 	    -
	----------------------------------------------------------------------
	Total        	-             	    4 	    2 	    3 	    1 	    0

 + Legend: - = not applicable, 0 = solver not compatible or not installed, 1 = solver installed.

 > You can solve LP problems using: 'gurobi' - 'glpk' - 'pdco' 
 > You can solve MILP problems using: 'gurobi' - 'glpk' 
 > You can solve QP problems using: 'gurobi' - 'pdco' 
 > You can solve MIQP problems using: 'gurobi' 
 > You can solve NLP problems using: 

 > Checking for available updates ...
 > There are 7827 new commit(s) on <master> and 0 new commit(s) on <develop> [800dcf @ master]
 > You can update The COBRA Toolbox by running updateCobraToolbox() (from within MATLAB).
Converting COBRA structure to RAVEN..

***************************************************************
   GECKO: Adding enzyme constraints to a genome-scale model
***************************************************************

Getting genome-scale model ready... Done!

==================
Generating ecModel:
==================
Retrieving EC numbers............................................ Done!
Matching kcats............................................ Done!
Adding enzymes to reactions............................................................... Done!
Improving model with curated data....................................................................................... Done!
Removing repeated rxn: r_0226No2 & r_0226No3
Removing repeated rxn: r_0438No1 & r_0438No2
Removing repeated rxn: r_0438No1 & r_0438No3
Removing repeated rxn: r_0438No1 & r_0438No4
Removing repeated rxn: r_0438No2 & r_0438No3
Removing repeated rxn: r_0438No2 & r_0438No4
Removing repeated rxn: r_0438No3 & r_0438No4
Removing repeated rxn: r_0439No1 & r_0439No2
Merging reactions: arm_r_0439 & r_0439No1
Merging reactions: arm_r_0543 & r_0543No1
Merging reactions: arm_r_1838 & r_1838No1
Removing unused protein: P00424
Removing unused protein: P18496
Removing unused protein: P22135
Removing unused protein: P32453
Removing unused protein: Q3E7B6
Removing incorrect pathways... Done!

==============================================================
Generating ecModel with shared pool assumption (ecModel_batch):
==============================================================
Calculating total abundance.................................................................... Done!
WARNING: Reaction r_1663 is not present in the reaction list

WARNING: Reaction r_4062 is not present in the reaction list

WARNING: Reaction r_4064 is not present in the reaction list

Matching data to enzymes in model... Done!
Estimating GAM.............................................................. Done!
Fitted GAM = 27.4 -> Error = 0.1816
[Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information, click <a href="matlab:opengl('problems')">here</a>.] 
Total protein amount measured = 0 g/gDW
Total enzymes measured = 0 enzymes
Enzymes in model with 0 g/gDW = 0 enzymes
Total protein amount not measured = 0.5 g/gDW
Total enzymes not measured = 968 enzymes
Total protein in model = 0.5 g/gDW
The ECmodel is overconstrained!
******************* Limiting Kcats curation *******************
*Iteration #1
 Automatic search // EC#: 5.4.99.7
  Protein:P38604 Rxn#:3751 name: lanosterol synthase (No1)
  prev_Kcat:0.0019367 new_Kcat:4.0763 CC:0.63672 Err:-61.0431%
*Iteration #2
 Automatic search // EC#: 6.3.5.3
  Protein:P38972 Rxn#:2991 name: 5'-phosphoribosylformyl glycinamidine synthetase (No1)
  prev_Kcat:0.05 new_Kcat:5.0675 CC:0.36184 Err:-47.1166%
*Iteration #3
 Automatic search // EC#: 4.2.1.20
  Protein:P00931 Rxn#:4155 name: tryptophan synthase (indoleglycerol phosphate) (No1)
  prev_Kcat:0.022301 new_Kcat:775.75 CC:0.41185 Err:-25.3069%
*Iteration #4
 Automatic search // EC#: 6.3.4.- 6.3.4.9 6.3.4.10 6.3.4.11 6.3.4.15
  Protein:P48445 Rxn#:3031 name: acetyl-CoA carboxylase, reaction (No1)
  prev_Kcat:1.23 new_Kcat:450000 CC:0.059866 Err:-20.8306%
*Iteration #5
 Automatic search // EC#: 2.1.1.14
  Protein:P05694 Rxn#:3781 name: methionine synthase (No1)
  prev_Kcat:0.33 new_Kcat:3.5 CC:0.046422 Err:-17.513%
*Iteration #6
 Automatic search // EC#: 2.7.6.1
  Protein:P32895 Rxn#:3984 name: phosphoribosylpyrophosphate synthetase (No1)
  prev_Kcat:0.65999 new_Kcat:1170 CC:0.044464 Err:-13.8436%
*Iteration #7
 Automatic search // EC#: 4.1.1.65
  Protein:P39006 Rxn#:4659 name: PS decarboxylase (1-16:1, 2-16:1), mitochondrial membrane (No1)
  prev_Kcat:0.053334 new_Kcat:366.6667 CC:0.041758 Err:-10.2424%
*Iteration #8
 Automatic search // EC#: 1.1.1.302
  Protein:P33312 Rxn#:2909 name: 2,5-diamino-6-ribosylamino-4(3H)-pyrimidinone 5'-phosphate reductase (NADPH) (No1)
  prev_Kcat:0.00066666 new_Kcat:0.00066667 CC:0.042829 Err:-10.2424%
*Iteration #9
 Automatic search // EC#: 2.3.1.15 2.3.1.42
  Protein:P36148 Rxn#:4383 name: glycerol-3-phosphate acyltransferase (16:1), ER membrane (No2)
  prev_Kcat:0.0918 new_Kcat:9.9733 CC:0.038586 Err:-6.8086%
***************************************************************
Fitting sigma factor....................... Done!
Saving simulation results files...
File successfully saved.
Sigma factor (fitted for growth on glucose): 0.49

=============
Saving models:
=============
Saving ecYeastGEMv8.4.2:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.
Saving ecYeastGEM_batchv8.4.2:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
That's smart @BenjaSanchez. The fix is now implemented https://github.com/SysBioChalmers/ecModels/commit/2affb845ea0464e9e76ff91bb59df9164d72a832. I'm looking forward to a nice upcoming PR for `ecMouseGEM`.

**Comment by IVANDOMENZAIN** [comment]
> That's smart @BenjaSanchez. The fix is now implemented [5bed492](https://github.com/SysBioChalmers/ecModels/commit/5bed49235cb2b1cc4e3d98fe4a713cf81f672cac). I'm looking forward to a nice upcoming PR for `ecMouseGEM`.

@mihai-sysbio should we replicate that commit in PR #53  prior to merge with `master`?

**Comment by mihai-sysbio** [comment]
I believe it's done already.

**Comment by IVANDOMENZAIN** [comment]
> > @mihai-sysbio should we replicate that commit in PR #53 prior to merge with `master`?
> 
> I believe it's done already.

Yes, i replicated it there last night, forgot to give you an update here

**Pull request closed without merging**
