### PR TITLE
refactor: github actions context

### PR DESCRIPTION
**Pull request by mihai-sysbio**
The repository name, hard-coded in the workflow, was replaced with an environment variable provided by default by the action context. Also, `config.ini` was updated with the full path for the new runner.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
Do you think this is ready to be merged in @IVANDOMENZAIN ?

**Comment by IVANDOMENZAIN** [comment]
> Do you think this is ready to be merged in @IVANDOMENZAIN ?

It seems that yes, the PR is very specific and the current run has confirmed that these changes have worked. 

But let's wait until the current automated run is over. It seems that it is going well, as it is creating PRs (#38  and #39). Let's not close the new PRs until the run is over so that we can check which of them are created. For instance, I can see that no PR was created for `ecYeastGEM` [this time](https://github.com/SysBioChalmers/ecModels/actions) (it should be the first one in the pipeline according to the current structure), any potential explanation for this @mihai-sysbio?

**Comment by IVANDOMENZAIN** [comment]
> > Do you think this is ready to be merged in @IVANDOMENZAIN ?
> 
> It seems that yes, the PR is very specific and the current run has confirmed that these changes have worked.
> 
> But let's wait until the current automated run is over. It seems that it is going well, as it is creating PRs (#38 and #39). Let's not close the new PRs until the run is over so that we can check which of them are created. For instance, I can see that no PR was created for `ecYeastGEM` [this time](https://github.com/SysBioChalmers/ecModels/actions) (it should be the first one in the pipeline according to the current structure), any potential explanation for this @mihai-sysbio?

@mihai-sysbio it seems that all the corresponding branches are created with non-empty commits that reflect the changes to the models and config (see attached image), however not all the PRs are being created.
Screen Shot 2021-02-11 at 18 00 43

**Comment by mihai-sysbio** [comment]
There were several issues with the installation being incomplete, eg Gurobi and libSBML version files missing (they need to be manually added), something about Raven/Cobra not being added to the path, and even `hub` not being installed.
It would be easier for me to understand what's going on if the board would be wiped clean by merging this PR and closing all the "update" ones. But we can of course allow it to finish, just to see if any other model besides `ecYeastGEM` doesn't get a PR.

**Comment by IVANDOMENZAIN** [comment]
> There were several issues with the installation being incomplete, eg Gurobi and libSBML version files missing (they need to be manually added), something about Raven/Cobra not being added to the path, and even `hub` not being installed.
> It would be easier for me to understand what's going on if the board would be wiped clean by merging this PR and closing all the "update" ones. But we can of course allow it to finish, just to see if any other model besides `ecYeastGEM` doesn't get a PR.

Alright! we merge this one as soon as the run finishes and we get the overall picture of the "update" PRs.

**Review by IVANDOMENZAIN — APPROVED** [review]

**Comment by mihai-sysbio** [comment]
I'm merging this in, hoping that the newly updated license will not hamper the creation of PRs. Sadly the license is valid for only 3 months at a time.

**Pull request merged**
