### PR TITLE
update ecMouseGEM based on v1.1.0

### PR DESCRIPTION
**Pull request by automator-metatlas**
```matlab
MATLAB is selecting SOFTWARE OPENGL rendering.

                                                                              < M A T L A B (R) >
                                                                    Copyright 1984-2020 The MathWorks, Inc.
                                                                R2020b Update 3 (9.9.0.1538559) 64-bit (glnxa64)
                                                                               November 23, 2020

 
To get started, type doc.
For product information, visit www.mathworks.com.
 

***************************************************************
   GECKO: Adding enzyme constraints to a genome-scale model
***************************************************************

Getting genome-scale model ready...[Warning: Potentially problematic ") AND (", ") AND" or "AND ("relationships found in

  - grRule #MA_07161: (Polr3g or Polr3gl) and (Papola or Papolb or Papolg or Tent2) and (Tut1 or Tut4 or Tut7) and Gm14567 and Mtpap and Polr1a and Polr1b and Polr1c and Polr1d
  and Polr1e and Polr2a and Polr2b and Polr2c and Polr2d and Polr2e and Polr2f and Polr2g and Polr2h and Polr2i and Polr2j and Polr2l and Polr3a and Polr3b and Polr3c and Polr3d
  and Polr3e and Polr3f and Polr3h and Polr3k and Polrmt
  - grRule #MA_07162: (Polr3g or Polr3gl) and (Papola or Papolb or Papolg or Tent2) and (Tut1 or Tut4 or Tut7) and Gm14567 and Mtpap and Polr1a and Polr1b and Polr1c and Polr1d
  and Polr1e and Polr2a and Polr2b and Polr2c and Polr2d and Polr2e and Polr2f and Polr2g and Polr2h and Polr2i and Polr2j and Polr2l and Polr3a and Polr3b and Polr3c and Polr3d
  and Polr3e and Polr3f and Polr3h and Polr3k and Polrmt
  - grRule #MA_02512: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_02513: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_02410: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_02411: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03464: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03468: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03469: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_01166: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01168: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_01209: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01211: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_01258: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01260: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_01275: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01277: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_01293: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01294: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_01300: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01301: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03059: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03060: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03064: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03065: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03068: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03069: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03072: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03073: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03076: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03077: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03080: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03081: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03084: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03085: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03088: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03089: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03092: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03093: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03096: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03097: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03100: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03101: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03104: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03328: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03329: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03332: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03333: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03336: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03337: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03340: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03341: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03344: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03345: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03348: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03349: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03352: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03353: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03367: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03368: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03372: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03373: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03503: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03505: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03509: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03510: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03514: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03515: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03304: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03305: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03309: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03310: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03314: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03315: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03319: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03320: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03358: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03359: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_03362: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_03363: (Acaa1a or Acaa1b) and Myo5b
  - grRule #MA_01644: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01642: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01646: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01706: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #MA_01708: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #ATPasel: ((Atp6v0a4 and Atp6v0b and Atp6v0c and Atp6v0d2 and Atp6v0e) or (Atp6v0a2 and Atp6v0b and Atp6v0c and Atp6v0d2 and Atp6v0e) or (Atp6v0a4 and Atp6v0b and
  Atp6v0c and Atp6v0d1 and Atp6v0e) or (Atp6v0a1 and Atp6v0b and Atp6v0c and Atp6v0d2 and Atp6v0e) or (Atp6v0a1 and Atp6v0b and Atp6v0c and Atp6v0d1 and Atp6v0e) or (Atp6v0b and
  Atp6v0c and Atp6v0d1 and Atp6v0e and Tcirg1) or (Atp6v0a2 and Atp6v0b and Atp6v0c and Atp6v0d1 and Atp6v0e) or (Atp6v0b and Atp6v0c and Atp6v0d2 and Atp6v0e and Tcirg1)) and
  ((Atp6v1a and Atp6v1b2 and Atp6v1c2 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g2 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c1 and Atp6v1d and Atp6v1e1 and Atp6v1f and
  Atp6v1g2 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c1 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g3 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c2 and Atp6v1d and
  Atp6v1e2 and Atp6v1f and Atp6v1g3 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c2 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g2 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and
  Atp6v1c2 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g2 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c1 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g2 and Atp6v1h) or
  (Atp6v1a and Atp6v1b2 and Atp6v1c1 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g3 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c1 and Atp6v1d and Atp6v1e1 and Atp6v1f and
  Atp6v1g3 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c1 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g2 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c1 and Atp6v1d and
  Atp6v1e2 and Atp6v1f and Atp6v1g3 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c2 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g3 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and
  Atp6v1c2 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g2 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c2 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g3 and Atp6v1h) or
  (Atp6v1a and Atp6v1b1 and Atp6v1c2 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g3 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c2 and Atp6v1d and Atp6v1e2 and Atp6v1f and
  Atp6v1g1 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c2 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g1 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c2 and Atp6v1d and] 
[  Atp6v1e1 and Atp6v1f and Atp6v1g1 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c1 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g1 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and
  Atp6v1c1 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g1 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c2 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g1 and Atp6v1h) or
  (Atp6v1a and Atp6v1b2 and Atp6v1c1 and Atp6v1d and Atp6v1e1 and Atp6v1f and Atp6v1g1 and Atp6v1h) or (Atp6v1a and Atp6v1b1 and Atp6v1c1 and Atp6v1d and Atp6v1e1 and Atp6v1f and
  Atp6v1g1 and Atp6v1h) or (Atp6v1a and Atp6v1b2 and Atp6v1c1 and Atp6v1d and Atp6v1e2 and Atp6v1f and Atp6v1g2 and Atp6v1h))
  - grRule #FAOXC16080x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC180x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC183806x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC18480x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC200180x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC2051843x: ((Acaa1a or Acaa1b) and Acox1 and Ehhadh) or ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4)
  - grRule #FAOXC2242046x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC2252053x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC226205x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC240200x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC241181x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC2442246x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC2452253x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC2452256x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC246226x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #FAOXC260240x: ((Acaa1a or Acaa1b) and Acox1 and Hsd17b4) or ((Acaa1a or Acaa1b) and Acox1 and Ehhadh)
  - grRule #PEROXx: (Acaa1a or Acaa1b) and Acox3 and Ehhadh and Hsd17b4
  - grRule #r1481: (Acaa2 and Hadhb) or ((Acaa1a or Acaa1b) and Hadhb)
  - grRule #FAOXC101C8x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC102C81x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC10C8x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC10DCC8DCx: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC11BRC9BRx: (Acaa1a or Acaa1b) and Acox3 and Ehhadh and Hsd17b4
  - grRule #FAOXC121C10x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC123C102x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC12C10x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC12DCC10DCx: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC13BRC11BRx: (Acaa1a or Acaa1b) and Acox3 and Ehhadh and Hsd17b4
  - grRule #FAOXC141C121x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC142C122x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC143C123x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC14C12x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC14DCC12DCx: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC15BRC13BRx: (Acaa1a or Acaa1b) and Acox3 and Ehhadh and Hsd17b4
  - grRule #FAOXC161C141x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC163C142x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC164C143x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC16C14x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC16DCC14DCx: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC181C161x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC184C163x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC184C164x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC201C181x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC205C184x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC221C201x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC225C204x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC22C20x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC241C221x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC24C22x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC61C4x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4
  - grRule #FAOXC6C4x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC6DCC4DCx: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC81C61x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC8C6x: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FAOXC8DCC6DCx: (Acaa1a or Acaa1b) and Acox1 and Ehhadh and Hsd17b4
  - grRule #FOAXC122C101x: (Acaa1a or Acaa1b) and Ehhadh and Hsd17b4

 This kind of relationships should only be present in  reactions catalysed by complexes of isoenzymes e.g.

  - (G1 or G2) and (G3 or G4)

 For these cases modify the grRules manually, writing all the possible combinations e.g.

  - (G1 and G3) or (G1 and G4) or (G2 and G3) or (G2 and G4)

 For other cases modify the correspondent grRules avoiding:

  1) Overall container brackets, e.g.
        "(G1 and G2)" should be "G1 and G2"

  2) Single unit enzymes enclosed into brackets, e.g.
        "(G1)" should be "G1"

  3) The use of uppercases for logical operators, e.g.
        "G1 OR G2" should be "G1 or G2"

  4) Unbalanced brackets, e.g.
        "((G1 and G2) or G3" should be "(G1 and G2) or G3"
] 
[> In standardizeGrRules>findPotentialErrors (line 155)
In standardizeGrRules (line 38)
In preprocessModel (line 27)
In enhanceGEM (line 51)] 
 Done!

==================
Generating ecModel:
==================
Retrieving EC numbers...WARNING: Potentially problematic ") AND (" in the grRules for reaction(s): 
	MA_07161
	MA_07162
	MA_02512
	MA_02513
	MA_02410
	MA_02411
	MA_03464
	MA_03468
	MA_03469
	...and 133 more

...................................................................................................................................
```

### CODE REVIEW

**Comment by IVANDOMENZAIN** [comment]
@Hao-Chalmers it seems that there are a lot of non-standard grRules in the original mouseGEM, the RAVEN function avoids the correction of this kind of rules, as the possible combinations for nested ORs in enzyme complexes can be untractable for some cases. This, at the end, is expected to have a considerable impact in the resulting ecModel as more than 133 grRules present these issues and the relation between enzymes and reactions is retrieved from this model field by GECKO. 

Any thoughts on how to asses this problem? (probably not crucial for having a functional implementation of the automated `ecModels pipeline` for mouseGEM, but more regarding the performance of the ecModel).

**Comment by Hao-Chalmers** [comment]
Ah, okay. Will look into these error-prone grRules.

**Comment by IVANDOMENZAIN** [comment]
> Ah, okay. Will look into these error-prone grRules.

You can assess them by running the RAVEN `standardizeGrRules` function with the original mouseGEM, make sure of giving the `embedded` input variable a value = false, so that the function can show you a more detailed picture of the conflicting grRules and even suggest some guidelines.

**Comment by Hao-Chalmers** [comment]
By running `standardizeGrRules`, a total of 142 grRules were complained. The majority of these (138 out of 142) are due to the duplication of the human gene ACAA1 in mouse (as a form of "Acaa1a or Acaa1b"), while ACAA1 itself is a subunit of several enzyme complexes that catalyzing a number of reactions.

@IVANDOMENZAIN if `standardizeGrRules` can convert simple cases, such as 
from: **(Acaa1a or Acaa1b) and Myo5b**
to:   **(Acaa1a and Myo5b) or (Acaa1b and Myo5b)**

**Comment by Hao-Chalmers** [comment]
Can this automator works with any branch, or it has to load mode from the master branch? @IVANDOMENZAIN @mihai-sysbio

**Comment by IVANDOMENZAIN** [comment]
> Can this automator works with any branch, or it has to load mode from the master branch? @IVANDOMENZAIN @mihai-sysbio

@Hao-Chalmers Yes, it can be triggered by any push event to any branch other than `master`  and those created by the automator itself.

**Comment by Hao-Chalmers** [comment]
if I understand correctly, this automator uptakes Matlab file as input?

**Comment by IVANDOMENZAIN** [comment]
> if I understand correctly, this automator uptakes Matlab file as input?

@Hao-Chalmers do you refer to the input model file? if so, then the answer is that it is flexible, it can take either the MATLAB or the SBML file of the models. For the `mouseGEM` case we are currently using the `.mat` file available in master.

**Comment by Hao-Chalmers** [comment]
Thanks for the answer. A testing branch will be made for hosting mouse GEM with fixed grRules for EC modeling purpose.

**Comment by IVANDOMENZAIN** [comment]
> Thanks for the answer. A testing branch will be made for hosting mouse GEM with fixed grRules for EC modeling purpose.

@Hao-Chalmers good to know! just tag me in the branch when the model is ready for testing, then I can take care of its integration into the automated pipeline and inform you about the results.

**Comment by Hao-Chalmers** [comment]
@IVANDOMENZAIN please try out new mouse model from this [test4GECKO](https://github.com/SysBioChalmers/Mouse-GEM/tree/test4GECKO/model) branch.

**Comment by Hao-Chalmers** [comment]
@IVANDOMENZAIN @mihai-sysbio look forward to a testing with the model in [test4GECKO](https://github.com/SysBioChalmers/Mouse-GEM/tree/test4GECKO/model) branch.

**Comment by IVANDOMENZAIN** [comment]
> @IVANDOMENZAIN @mihai-sysbio look forward to a testing with the model in [test4GECKO](https://github.com/SysBioChalmers/Mouse-GEM/tree/test4GECKO/model) branch.

Will give it a first attempt tonight @Hao-Chalmers, gonna let you know about the results

**Comment by mihai-sysbio** [comment]
Have a look at the [latest run](https://github.com/SysBioChalmers/ecModels/actions/runs/682276022) when loading `Mouse-GEM.mat` from the raw url for the `test4GECKO` branch.

**Comment by IVANDOMENZAIN** [comment]
@Hao-Chalmers @mihai-sysbio here you have some updates regarging `ecMouseGEM` generation.

- The problem in the [automated run](https://github.com/SysBioChalmers/ecModels/actions/runs/682276022) indicated by Mihail, was caused by a problem with parsing the model version. GECKO tried to get it from the `model.version` field, however this is an empty string in the current GEM provided by Hao, so I just added a temporary `version=0` in the `preprocessModel` function in GECKO (commit a2361c4a158aaa6f3992a7d1fde214bfe8da4bc8). I assume that a proper version string is planned to be included in MouseGEM in the future.

- The next issue was found in the step of `getEnzymeCodes` in GECKO. Namely, for this organism it is the case that some genes match to multiple proteins in the uniprot database (maybe different splicing variants), see attached file [MATLAB_log_ecMouseGEM.txt](https://github.com/SysBioChalmers/ecModels/files/6208168/MATLAB_log_ecMouseGEM.txt) for further details. This is currently handled by GECKO but the `mouseGEM` case allowed to find some bugs fixed in commit 27c62281e2eedcc5672ca137e150eca35271321e. I used the option `ignore` of this GECKO function, which will just take the first protein match for each of these genes. Another option is that the GECKO pipeline can also include all protein matches for a given gene and treat them as actual isoenzymes. @Hao-Chalmers could you take a look to the attached file and inform me which option do you think is better for these cases? 

- The last issue (so far), was related to a non-standard grRule, once again but now further in the pipeline, actually even when the first ecModel structure was obtained. As Hao has curated most of these rules and  just one conflict was remaining I decided to ignore such grRule in order to avoid the introduction of potentially erroneous enzyme complexes. This was done in commit 6ebc216887822c1fe7355b32b73f413ed0d09d34, using the same approach as the [latest ecHumanGEM reconstruction](https://github.com/SysBioChalmers/ecModels/pull/77).

**Comment by Hao-Chalmers** [comment]
@IVANDOMENZAIN thanks for checking this.

> The problem in the automated run indicated by Mihail, was caused by a problem with parsing the model version. GECKO tried to get it from the model.version field, however this is an empty string in the current GEM provided by Hao, so I just added a temporary version=0 in the preprocessModel function in GECKO (commit a2361c4). I assume that a proper version string is planned to be included in MouseGEM in the future.

this model is from `develop` branch where there is no version assigned usually. It's okay to use `0` for testing purpose.

The next issue was found in the step of getEnzymeCodes in GECKO. Namely, for this organism it is the case that some genes match to multiple proteins in the uniprot database (maybe different splicing variants), see attached file MATLAB_log_ecMouseGEM.txt for further details. This is currently handled by GECKO but the mouseGEM case allowed to find some bugs fixed in commit 27c6228. I used the option ignore of this GECKO function, which will just take the first protein match for each of these genes. Another option is that the GECKO pipeline can also include all protein matches for a given gene and treat them as actual isoenzymes. @Hao-Chalmers could you take a look to the attached file and inform me which option do you think is better for these cases?

Will look into this.

The last issue (so far), was related to a non-standard grRule, once again but now further in the pipeline, actually even when the first ecModel structure was obtained. As Hao has curated most of these rules and just one conflict was remaining I decided to ignore such grRule in order to avoid the introduction of potentially erroneous enzyme complexes. This was done in commit 6ebc216, using the same approach as the latest ecHumanGEM reconstruction.

yes, just ignore them that shouldn't have much impact to downstream work. And their ultimate fix should be done in Human-GEM.

**Comment by Hao-Chalmers** [comment]
@IVANDOMENZAIN unique UniProt ids have been provided in a `genes.tsv` file (the 4th column) newly uploaded to the test branch by this [commit](2be300440ce604bdab25680f09e6e1371aa0b3af). Hope this helps.

**Comment by IVANDOMENZAIN** [comment]
> @IVANDOMENZAIN unique UniProt ids have been provided in a `genes.tsv` file (in the 4th column) newly uploaded to the test branch by this [commit](2be300440ce604bdab25680f09e6e1371aa0b3af). Hope this helps.


Thanks @Hao-Chalmers will look into this :)

**Pull request closed without merging**
